spring:
  application:
    name: dubbo-consumer-demo-zk

server:
  port: 8080


endpoints:
  dubbo:
    enabled: true


management:
  server:
    port: 8081
  endpoint:
    dubbo-configs:
      enabled: true
    dubbo:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-properties:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-references:
      enabled: true
  health:
    dubbo:
      status:
        defaults: memory
dubbo:
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    timeout: 15000
  protocol:
    port: 12345
    name: dubbo
  application:
    name: dubbo-consumer-demo-zk-facade
    id: dubbo-consumer-demo-zk-facade
  qos:
    port: 22223
demo:
  service:
    version: 1.0.0
