sharding:
  jdbc:
    datasource:
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/nacos?useSSL=true&characterEncoding=UTF-8
        username: root
        password: root
        initial-size: 1
        min-idle: 1
        max-active: 200
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: "SELECT 'x'"
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
      names: ds0
    config:
      sharding:
        tables:
          order_info:
            table-strategy:
              standard:
                sharding-column: order_id
                precise-algorithm-class-name: com.fulihui.demo.zk.dal.shard.UserIdAlgorithm
            actual-data-nodes: ds0.order_info_$->{0..9}

