spring:
  profiles:
    active: shard
  application:
    name: dubbo-provider-demo-zk-service


mybatis:
  typeAliasesPackage: com.fulihui.demo.zk.dal.dao
  mapperLocations: classpath*:sqlmap/*.xml





server:
  port: 8090
management:
  endpoint:
    dubbo-configs:
      enabled: true
    dubbo:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-properties:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-references:
      enabled: true
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool
dubbo:
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    timeout: 15000
  protocol:
    port: 12345
    name: dubbo
    status: server
    serialization: fastjson
    threads: 2000
  application:
    qos:
      port: 22222
      enable: true
    name: dubbo-provider-demo-zk-service
    id: dubbo-provider-demo-zk-service
  scan:
    basePackages: com.fulihui.demo.zk.service

demo:
  service:
    version: 1.0.0



